# Turned the data on the website into python lists and dictionary

possible_ingredients = [
    "genet",
    "topinambour",
    "pissenlit",
    "cassis",
    "lin",
    "carotte sauvage",
    "cumin",
    "cerfeuil commun",
    "melisse citronnelle",
    "groseillier",
    "sauge",
    "moutarde",
    "morelle de balbis",
    "ciboulette chinoise",
    "anis",
    "panais",
    "courgette",
    "cornichon",
    "bourrache officinale",
    "sarriette",
    "feve",
    "melon",
    "tournesol",
    "echalote",
    "thym",
    "romarin",
    "achillee millefeuille",
    "prunier",
    "framboisier",
    "cerisier",
    "rue fetide",
    "navet",
    "roquette",
    "chicoree",
    "epinard",
    "artichaut",
    "persil",
    "agrume",
    "lavande",
    "rosier",
    "tanaisie commune",
    "courge",
    "origan",
    "vigne",
    "poirier commun",
    "trefle blanc",
    "mache",
    "potiron",
    "mais",
    "haricot",
    "pasteque",
    "cosmos",
    "tomate",
    "basilic",
    "fenouil",
    "celeri",
    "betterave",
    "coriandre",
    "pois",
    "camomille allemande",
    "kiwi",
    "pomme de terre",
    "asperge",
    "concombre",
    "aneth",
    "chou",
    "laitue",
    "oignon",
    "fraisier des bois",
    "souci",
    "phacelie",
    "pommier",
    "ciboulette",
    "pecher",
    "ail",
    "carotte",
    "poireau",
    "cresson",
    "radis",
]

categories = [
    "auxiliaire",
    "aromate",
    "fleur",
    "fruit",
    "legume",
    "nuisible",
    "arbre",
    "cereale",
]

# possible ingredients per category
ingredients_per_category = {
    "fleur": [
        "genet",
        "pissenlit",
        "carotte sauvage",
        "morelle de balbis",
        "bourrache officinale",
        "tournesol",
        "achillee millefeuille",
        "lavande",
        "rosier",
        "tanaisie commune",
        "trefle blanc",
        "cosmos",
        "camomille allemande",
        "souci",
        "phacelie",
    ],
    "legume": [
        "topinambour",
        "panais",
        "courgette",
        "cornichon",
        "feve",
        "echalote",
        "navet",
        "roquette",
        "chicoree",
        "epinard",
        "artichaut",
        "courge",
        "mache",
        "potiron",
        "mais",
        "haricot",
        "tomate",
        "fenouil",
        "celeri",
        "betterave",
        "pois",
        "pomme de terre",
        "asperge",
        "concombre",
        "chou",
        "laitue",
        "oignon",
        "ail",
        "carotte",
        "poireau",
        "cresson",
        "radis",
    ],
    "fruit": [
        "cassis",
        "groseillier",
        "melon",
        "prunier",
        "framboisier",
        "cerisier",
        "agrume",
        "vigne",
        "poirier commun",
        "pasteque",
        "kiwi",
        "fraisier des bois",
        "pommier",
        "pecher",
    ],
    "cereale": ["lin"],
    "aromate": [
        "cumin",
        "cerfeuil commun",
        "melisse citronnelle",
        "sauge",
        "moutarde",
        "ciboulette chinoise",
        "anis",
        "sarriette",
        "thym",
        "romarin",
        "rue fetide",
        "persil",
        "origan",
        "basilic",
        "coriandre",
        "aneth",
        "ciboulette",
    ],
}

adjascents = {
    "achillee millefeuille": ["framboisier", "romarin", "mais"],
    "agrume": [
        "lavande",
        "tanaisie commune",
        "absinthe",
        "oeillet d'inde",
        "rosier d'inde",
    ],
    "ail": [
        "pecher",
        "pommier",
        "poirier commun",
        "prunier",
        "chicoree",
        "pissenlit",
        "topinambour",
        "tomate",
        "fraisier des bois",
        "framboisier",
        "rosier",
    ],
    "aneth": ["chou", "concombre", "cornichon", "bette", "laitue", "oignon"],
    "anis": ["coriandre"],
    "artichaut": ["chou", "laitue", "epinard", "persil", "capucine", "poireau"],
    "asperge": [
        "pomme de terre",
        "concombre",
        "persil",
        "tomate",
        "cornichon",
        "poireau",
        "pois",
        "courge",
        "basilic",
        "rosier d'inde",
        "capucine",
    ],
    "aubergine": ["haricot"],
    "basilic": [
        "tomate",
        "piment",
        "concombre",
        "cornichon",
        "courge",
        "melon",
        "chou",
        "feve",
        "courgette",
        "fenouil",
        "asperge",
    ],
    "betterave": [
        "laitue",
        "carotte",
        "oignon",
        "chou",
        "celeri",
        "coriandre",
        "panais",
    ],
    "bourrache officinale": ["fraisier des bois", "haricot"],
    "camomille allemande": ["chou", "oignon", "pois", "pomme de terre"],
    "carotte": [
        "poireau",
        "ail",
        "oignon",
        "echalote",
        "ciboulette",
        "betterave",
        "pois",
        "radis",
        "laitue",
        "roquette",
        "panais",
        "tomate",
        "haricot",
        "piment",
        "lin",
        "romarin",
        "sauge",
        "absinthe",
        "coriandre",
    ],
    "carotte sauvage": ["chou"],
    "cassis": [
        "ciboulette",
        "absinthe",
        "tanaisie commune",
        "carotte",
        "oignon",
        "navet",
    ],
    "celeri": [
        "chou",
        "poireau",
        "fenouil",
        "tomate",
        "haricot",
        "pois",
        "concombre",
        "cornichon",
        "bette",
        "betterave",
        "courgette",
        "courge",
        "potiron",
    ],
    "cerfeuil commun": ["radis", "laitue", "chou", "chicoree"],
    "cerisier": ["raifort", "rue fetide"],
    "chicoree": ["epinard", "roquette", "souci"],
    "chou": [
        "aneth",
        "celeri",
        "haricot",
        "moutarde",
        "romarin",
        "tomate",
        "absinthe",
        "cosmos",
        "sauge",
        "thym",
        "laitue",
        "epinard",
        "oeillet d'inde",
        "capucine",
        "pomme de terre",
        "feve",
        "pois",
        "melisse citronnelle",
        "coriandre",
        "potiron",
        "chicoree",
        "cerfeuil commun",
        "cumin",
        "camomille allemande",
        "bette",
        "basilic",
        "artichaut",
        "carotte sauvage",
        "coquelicot",
        "concombre",
        "cornichon",
        "panais",
        "trefle blanc",
        "phacelie",
        "matricaire inodore",
        "achillee millefeuille",
        "ray-grass",
        "sarrasin",
    ],
    "ciboulette": [
        "carotte",
        "pommier",
        "pecher",
        "groseillier",
        "rosier d'inde",
        "cassis",
        "fraisier des bois",
        "concombre",
        "courge",
    ],
    "ciboulette chinoise": ["tomate", "pomme de terre"],
    "concombre": [
        "asperge",
        "celeri",
        "chou",
        "haricot",
        "laitue",
        "mais",
        "pois",
        "fenouil",
        "tomate",
    ],
    "coriandre": [
        "chou",
        "carotte",
        "pois",
        "betterave",
        "concombre",
        "pomme de terre",
        "anis",
    ],
    "cornichon": [
        "asperge",
        "celeri",
        "chou",
        "haricot",
        "laitue",
        "pois",
        "tomate",
        "fenouil",
        "pomme de terre",
    ],
    "cosmos": ["chou", "tomate"],
    "courge": [
        "haricot",
        "asperge",
        "celeri",
        "chou",
        "laitue",
        "mache",
        "pois",
        "oignon",
        "basilic",
        "ciboulette",
        "coriandre",
        "origan",
        "capucine",
        "tanaisie commune",
        "tournesol",
    ],
    "courgette": [
        "asperge",
        "celeri",
        "chou",
        "fenouil",
        "haricot",
        "pois",
        "mache",
        "mais",
        "oignon",
        "radis",
    ],
    "cresson": ["poireau", "radis"],
    "cumin": ["chou", "pois", "fenouil", "absinthe", "tomate"],
    "echalote": ["carotte"],
    "epinard": [
        "chou",
        "rosier",
        "artichaut",
        "chicoree",
        "fraisier des bois",
        "haricot",
        "navet",
        "salsifis cultive",
        "radis",
    ],
    "fenouil": ["celeri", "poireau", "basilic"],
    "feve": ["chou", "pomme de terre", "mais", "laitue", "sarriette", "basilic"],
    "fraisier des bois": ["poireau", "ail", "ciboulette", "oignon", "pecher"],
    "framboisier": [
        "souci",
        "ail",
        "prunier",
        "achillee millefeuille",
        "rue fetide",
        "tanaisie commune",
    ],
    "genet": ["radis"],
    "groseillier": [
        "ciboulette",
        "absinthe",
        "tanaisie commune",
        "carotte",
        "oignon",
        "navet",
    ],
    "haricot": [
        "mais",
        "potiron",
        "chou",
        "melon",
        "pasteque",
        "carotte",
        "celeri",
        "feve",
        "pomme de terre",
        "epinard",
        "laitue",
        "bourrache officinale",
        "capucine",
        "sarriette",
        "tournesol",
        "absinthe",
    ],
    "inule visqueuse": ["olivier"],
    "kiwi": ["pomme de terre"],
    "laitue": [
        "chou",
        "carotte",
        "oignon",
        "pois",
        "cardon",
        "betterave",
        "courge",
        "feve",
        "fraisier des bois",
        "melon",
        "haricot",
        "navet",
        "poireau",
        "artichaut",
        "cerfeuil commun",
        "aneth",
        "lin",
    ],
    "laurier-sauce": ["persil"],
    "lavande": ["rosier", "agrume"],
    "lin": ["carotte", "laitue"],
    "mache": ["poireau", "oignon", "fraisier des bois", "trefle blanc", "potiron"],
    "mais": ["haricot", "pois", "potiron"],
    "marjolaine": ["piment"],
    "melisse citronnelle": ["chou"],
    "melon": ["laitue", "basilic"],
    "menthe": ["pommier", "poirier commun", "camomille allemande"],
    "morelle de balbis": ["pomme de terre"],
    "moutarde": ["chou", "laitue"],
    "navet": ["epinard", "fraisier des bois"],
    "oignon": ["carotte", "laitue", "mache", "radis", "trefle blanc"],
    "origan": ["courge", "concombre", "piment", "vigne"],
    "panais": ["radis", "betterave", "chou-rave", "oignon"],
    "pasteque": ["haricot", "tomate", "chou"],
    "patate douce": ["haricot"],
    "pecher": [
        "ail",
        "ciboulette",
        "raifort",
        "fraisier des bois",
        "chenopode blanc",
        "verge d'or",
        "tanaisie commune",
        "absinthe",
    ],
    "persil": ["tomate", "oignon", "artichaut", "asperge"],
    "phacelie": ["souci"],
    "pissenlit": ["ail"],
    "poireau": [
        "carotte",
        "celeri",
        "asperge",
        "laitue",
        "mache",
        "tomate",
        "fenouil",
        "artichaut",
        "moutarde",
        "cresson",
        "fraisier des bois",
    ],
    "poirier commun": ["trefle blanc", "nerprun alaterne"],
    "pois": ["ricin", "pomme de terre", "coriandre", "sarriette"],
    "poivron": ["tomate", "carotte", "chou"],
    "pomme de terre": [
        "kiwi",
        "asperge",
        "camomille allemande",
        "capucine",
        "celeri",
        "chanvre",
        "chou",
        "ciboulette chinoise",
        "coriandre",
        "feve",
        "feverolle",
        "haricot",
        "morelle de balbis",
        "pois",
        "radis",
        "souci",
    ],
    "pommier": [
        "phacelie",
        "panicaut",
        "camomille allemande",
        "potentille",
        "trefle blanc",
        "capucine",
        "nerprun alaterne",
        "noyer",
    ],
    "potiron": [
        "haricot",
        "mais",
        "asperge",
        "celeri",
        "chou",
        "laitue",
        "mache",
        "pois",
        "oignon",
        "basilic",
        "ciboulette",
        "coriandre",
        "origan",
        "capucine",
        "tanaisie commune",
        "tournesol",
        "pommier",
        "radis",
        "brocoli",
        "artichaut",
    ],
    "prunier": ["framboisier", "cerisier"],
    "radis": [
        "cresson",
        "genet",
        "cerfeuil commun",
        "panais",
        "carotte",
        "pois",
        "concombre",
        "cornichon",
        "epinard",
        "haricot",
        "celeri",
        "pomme de terre",
        "tomate",
        "oignon",
    ],
    "romarin": ["chou", "carotte", "achillee millefeuille"],
    "roquette": ["betterave", "carotte", "chicoree"],
    "rosier": [
        "lavande",
        "persil",
        "rue fetide",
        "tanaisie commune",
        "souci",
        "thym",
        "tomate",
        "epinard",
        "ail",
        "ciboulette",
        "oignon",
        "echalote",
    ],
    "rue fetide": ["cerisier", "rosier", "framboisier"],
    "sarriette": ["pois", "feve", "haricot"],
    "sauge": ["chou", "navet", "haricot", "carotte", "radis", "groseillier", "agrume"],
    "souci": [
        "fraisier des bois",
        "chicoree",
        "haricot",
        "pomme de terre",
        "tomate",
        "rosier",
        "framboisier",
    ],
    "tanaisie commune": ["pecher", "rosier"],
    "thym": ["chou", "rosier", "fraisier des bois"],
    "tomate": [
        "rosier d'inde",
        "oeillet d'inde",
        "cosmos",
        "camomille allemande",
        "chou",
        "geranium",
        "inule visqueuse",
        "pasteque",
        "concombre",
        "rosier",
        "carotte",
        "epinard",
        "haricot",
        "oignon",
        "persil",
        "poireau",
        "laitue",
    ],
    "topinambour": ["epinard"],
    "tournesol": ["courge", "haricot", "mais"],
    "trefle blanc": [
        "chou",
        "fraisier des bois",
        "mache",
        "poirier commun",
        "mais",
        "pommier",
        "vigne",
    ],
    "vigne": ["origan", "pecher", "pommier", "rosier", "trefle blanc"],
}

