# Turned the data on the website into python lists and dictionary

possible_ingredients = [
    "genet",
    "topinambour",
    "pissenlit",
    "cassis",
    "lin",
    "carotte sauvage",
    "cumin",
    "cerfeuil commun",
    "melisse citronnelle",
    "groseillier",
    "sauge",
    "moutarde",
    "morelle de balbis",
    "ciboulette chinoise",
    "anis",
    "panais",
    "courgette",
    "cornichon",
    "bourrache officinale",
    "sarriette",
    "feve",
    "melon",
    "tournesol",
    "echalote",
    "thym",
    "romarin",
    "achillee millefeuille",
    "prunier",
    "framboisier",
    "cerisier",
    "rue fetide",
    "navet",
    "roquette",
    "chicoree",
    "epinard",
    "artichaut",
    "persil",
    "agrume",
    "lavande",
    "rosier",
    "tanaisie commune",
    "courge",
    "origan",
    "vigne",
    "poirier commun",
    "trefle blanc",
    "mache",
    "potiron",
    "mais",
    "haricot",
    "pasteque",
    "cosmos",
    "tomate",
    "basilic",
    "fenouil",
    "celeri",
    "betterave",
    "coriandre",
    "pois",
    "camomille allemande",
    "kiwi",
    "pomme de terre",
    "asperge",
    "concombre",
    "aneth",
    "chou",
    "laitue",
    "oignon",
    "fraisier des bois",
    "souci",
    "phacelie",
    "pommier",
    "ciboulette",
    "pecher",
    "ail",
    "carotte",
    "poireau",
    "cresson",
    "radis",
]

categories = [
    "auxiliaire",
    "aromate",
    "fleur",
    "fruit",
    "legume",
    "nuisible",
    "arbre",
    "cereale",
]

# possible ingredients per category
ingredients_per_category = {
    "fleur": [
        "genet",
        "pissenlit",
        "carotte sauvage",
        "morelle de balbis",
        "bourrache officinale",
        "tournesol",
        "achillee millefeuille",
        "lavande",
        "rosier",
        "tanaisie commune",
        "trefle blanc",
        "cosmos",
        "camomille allemande",
        "souci",
        "phacelie",
    ],
    "legume": [
        "topinambour",
        "panais",
        "courgette",
        "cornichon",
        "feve",
        "echalote",
        "navet",
        "roquette",
        "chicoree",
        "epinard",
        "artichaut",
        "courge",
        "mache",
        "potiron",
        "mais",
        "haricot",
        "tomate",
        "fenouil",
        "celeri",
        "betterave",
        "pois",
        "pomme de terre",
        "asperge",
        "concombre",
        "chou",
        "laitue",
        "oignon",
        "ail",
        "carotte",
        "poireau",
        "cresson",
        "radis",
    ],
    "fruit": [
        "cassis",
        "groseillier",
        "melon",
        "prunier",
        "framboisier",
        "cerisier",
        "agrume",
        "vigne",
        "poirier commun",
        "pasteque",
        "kiwi",
        "fraisier des bois",
        "pommier",
        "pecher",
    ],
    "cereale": ["lin"],
    "aromate": [
        "cumin",
        "cerfeuil commun",
        "melisse citronnelle",
        "sauge",
        "moutarde",
        "ciboulette chinoise",
        "anis",
        "sarriette",
        "thym",
        "romarin",
        "rue fetide",
        "persil",
        "origan",
        "basilic",
        "coriandre",
        "aneth",
        "ciboulette",
    ],
}
